// Generated by `bun init`

declare module '*.svg' {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module '*.module.css' {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module '*.css' {
  // Plain CSS side-effect imports (e.g. react-toastify)
}

/**
 * Environment Variables
 * Type-safe access to environment variables via Bun.env
 *
 * Keep this in sync with .env.example whenever env vars are added, removed, or renamed.
 */
declare module 'bun' {
  interface Env {
    NODE_ENV?: 'development' | 'production' | 'test';

    // PostgreSQL — individual parts used to build the connection URL at runtime
    POSTGRES_SERVER?: string;
    POSTGRES_DB?: string;
    POSTGRES_USER?: string;
    POSTGRES_PASSWORD?: string;

    // Auth
    JWT_SECRET?: string;
    APP_URL?: string;

    // CORS — comma-separated list of allowed origins, or * to allow all
    CORS_ORIGIN?: string;

    // Seed
    SEED_ADMIN_EMAIL?: string;
    SEED_ADMIN_PASSWORD?: string;
    SEED_ADMIN_NAME?: string;

    // E2E — Playwright test user (defaults baked into e2e/global-setup.ts)
    E2E_TEST_EMAIL?: string;
    E2E_TEST_PASSWORD?: string;
    E2E_TEST_NAME?: string;

    // OpenTelemetry — optional, only active when OTEL_ENDPOINT is set
    OTEL_ENDPOINT?: string; // e.g. http://localhost:4318
    OTEL_SERVICE_NAME?: string; // defaults to "bun-boiler"

    // Rybbit Analytics — optional, only active when both are set
    // BUN_PUBLIC_ prefix is required for Bun to expose these to the frontend bundle
    BUN_PUBLIC_RYBBIT_HOST?: string; // e.g. http://localhost:8090
    BUN_PUBLIC_RYBBIT_SITE_ID?: string; // numeric site ID from the Rybbit dashboard
  }
}

/**
 * Augment import.meta.env so BUN_PUBLIC_* variables are named and typed
 * when accessed via import.meta.env in frontend (bundled) code.
 *
 * The base ImportMetaEnv interface in bun-types uses an index signature
 * ([key: string]: string | undefined), which accepts any key. This augmentation
 * adds explicit named properties so IDEs autocomplete and document them.
 */
interface ImportMetaEnv {
  // Rybbit Analytics — mirrors the Bun.env declarations above
  BUN_PUBLIC_RYBBIT_HOST?: string;
  BUN_PUBLIC_RYBBIT_SITE_ID?: string;
}
