// Generated by `bun init`

declare module '*.svg' {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module '*.module.css' {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module '*.css' {
  // Plain CSS side-effect imports (e.g. react-toastify)
}

/**
 * Environment Variables
 * Type-safe access to environment variables via Bun.env
 *
 * Keep this in sync with .env.example whenever env vars are added, removed, or renamed.
 */
declare module 'bun' {
  interface Env {
    NODE_ENV?: 'development' | 'production' | 'test';

    // PostgreSQL — individual parts used to build the connection URL at runtime
    POSTGRES_SERVER?: string;
    POSTGRES_DB?: string;
    POSTGRES_USER?: string;
    POSTGRES_PASSWORD?: string;

    // Auth
    JWT_SECRET?: string;
    APP_URL?: string;

    // CORS — comma-separated list of allowed origins, or * to allow all
    CORS_ORIGIN?: string;

    // Seed
    SEED_ADMIN_EMAIL?: string;
    SEED_ADMIN_PASSWORD?: string;
    SEED_ADMIN_NAME?: string;

    // E2E — Playwright test user (defaults baked into e2e/global-setup.ts)
    E2E_TEST_EMAIL?: string;
    E2E_TEST_PASSWORD?: string;
    E2E_TEST_NAME?: string;

    // OpenTelemetry — optional, only active when OTEL_ENDPOINT is set
    OTEL_ENDPOINT?: string; // e.g. http://localhost:4318
    OTEL_SERVICE_NAME?: string; // defaults to "bun-boiler"
  }
}
